public enum BasicTag { Basic, Physical, Bullet, Rocket, Arrow, 
    Explosive, Projectile, Summon, Sentry, Thrown, Magic, Sound, 
    Fire, Water, Grass, Electric, Ice, Fighting, Poison, Ground, 
    Flying, Psychic, Bug, Rock, Ghost, Dark, Dragon, Steel, Fairy, 
    Nuclear, Candy, Slime, Solar, Offensive, Defensive, Supportive, 
    Slow, Melee, Lobbed, Shadow, Spike, Piercing, Fel, Arcane, Hellfire, 
    Holy, Egyptian, Pirate, Cowboy, Futuristic, Arctic, Steampunk, 
    Retro, Tropical, Medieval, Jurassic, Roman, Chinese, Jungle, 
    Volcanic, Cosmic, Beast, Demon, Elemental, Mechanical, Aquatic, 
    Siren, Boar, Totem, Undead, Gourmet, Party, Sport, Science, 
    History, Hairy, Clock, Dance, Barrel, Mime, Tiny, Huge, Monster, 
    Professional, Horror, Army, Robot, Weapon, Location, Magenta, 
    Red, Orange, Yellow, Green, Cyan, Blue, Indigo, Violet, Black, 
    White, Gray };