using System;

[Flags]
public enum ElementalTag: int { 
    None = 0,
    Flaming = 1, 
    Watery = 1 << 1, 
    Nature = 1 << 2, 
    Electrical = 1 << 3, 
    Icey = 1 << 4, 
    MartialArt = 1 << 5, 
    Poisoned = 1 << 6, 
    Earthern = 1 << 7, 
    Aerial = 1 << 8, 
    Psychic = 1 << 9, 
    Beastly = 1 << 10, 
    Undead = 1 << 11, 
    Steel = 1 << 12, 
    Magical = 1 << 13, 
    Nuclear = 1 << 14, 
    Sugary = 1 << 15, 
    Slimy = 1 << 16, 
    Solar = 1 << 17, 
    Offensive = 1 << 18, 
    Defensive = 1 << 19, 
    Supportive = 1 << 20, 
    Melee = 1 << 21, 
    Lobbed = 1 << 22, 
    Unholy = 1 << 23, 
    Explosive = 1 << 24, 
    Spikey = 1 << 25, 
    Piercing = 1 << 26, 
    Hellfire = 1 << 27, 
    Holy = 1 << 28, 
    Light = 1 << 29, 
    Heavy = 1 << 30
}

[Flags]
public enum WeaponTag: int { 
    None = 0,
    ShortSword = 1, 
    LongSword = 1 << 1, 
    Spear = 1 << 2, 
    Boomerang = 1 << 3, 
    Flail = 1 << 4, 
    Whip = 1 << 5, 
    ThrowingMelee = 1 << 6, 
    Bow = 1 << 7, 
    AssaultRifle = 1 << 8, 
    LMG = 1 << 9, 
    Shotgun = 1 << 10, 
    Sniper = 1 << 11, 
    Akimbo = 1 << 12, 
    Minigun = 1 << 13, 
    Flamethrower = 1 << 14, 
    Pistol = 1 << 15, 
    SMG = 1 << 16, 
    SingleShot = 1 << 17, 
    RocketLauncher = 1 << 18, 
    GrenadeLauncher = 1 << 19, 
    LaserGun = 1 << 20, 
    Wand = 1 << 21, 
    Spellbook = 1 << 22, 
    Magic = 1 << 23, 
    Consumable = 1 << 24, 
    Bomb = 1 << 25, 
    Hazard = 1 << 26, 
    Summoner = 1 << 27, 
    Sentry = 1 << 28, 
    Primary = 1 << 29,
    Equipable = 1 << 30,
    Melee = ShortSword | LongSword | Spear | Boomerang | Flail | Whip | ThrowingMelee,
    Ranged = Bow | AssaultRifle | LMG | Shotgun | Sniper | Akimbo | Minigun | Flamethrower | Pistol | SMG | SingleShot | RocketLauncher | GrenadeLauncher | LaserGun,
    Magical = Wand | Spellbook | Magic,
    Rogue = Consumable | Bomb | Hazard,
    Rogue2 = Rogue | ThrowingMelee | Boomerang,
    Classed = Melee & Ranged & Magical & Rogue
}

public enum FoodTags: int {
    None = 0,
    Fruits = 1,
    Vegetables = 1 << 1,
    Fish = 1 << 2,
    Shellfish = 1 << 3,
    Meat = 1 << 4,
    Poultry = 1 << 5,
    Beans = 1 << 6,
    Nuts = 1 << 7,
    Eggs = 1 << 8,
    Milk = 1 << 9,
    Rice = 1 << 10,
    Corn = 1 << 11,
    Bread = 1 << 12,
    Noodles = 1 << 13,
    Fats = 1 << 14,
    Oils = 1 << 15,
    Sugars = 1 << 16,
    Beverage = 1 << 17,
    Protein = Fish | Shellfish | Meat | Poultry | Beans | Nuts | Eggs | Milk,
    Grains = Rice | Corn | Bread | Noodles,
    Fatty = Fats | Oils | Sugars
}